version: "2"

checks:
  method-lines:
    config:
      threshold: 50
  method-complexity:
    config:
      threshold: 10

plugins:
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
